### ISSUE TITLE
P0009: static extent preservation in subspan can't be QOI because of ABI compatibility

### ISSUE THREAD

**Issue by dhollman** [ORNL/cpp-proposals-pub#57]
The paper currently has the following note next to subspan:

> Note: it is quality of implementation whether static extents are preserved if possible. 

I doubt this will fly since the type of the return value is part of the ABI, and thus introduces an ABI dependence on QOI. We should probably remove this and specify the requirements for static extent preservation.

**Comment by hcedwar** [comment]
Yeah - I tightened up this clause and a lot of the subspan wording  in PR #55

**Comment by crtrott** [comment]
Though the main thing is that you added arbitrary layout conversions. Previously we had this as a subspan always being layout_stride and the function only being defined for basic_mdspan with one of the standard layouts. That reduced the amount of definition we needed to do. In fact other than the requirement of preserving static extents as static in order to not have a QOI dependent ABI, the subspan definition was complete for that case. We consciously sidestepped the generic layout convertibility previously to keep the proposal simple. Note that we neither define conversions of layouts into each other. 

This btw. brings another awkward problem with it: through subspan you basically now require that arbitrary layout (i.e. custom layout) conversions are possible, since there is no require clause which limits what layout to which layout works. That means the post conditions are not actually fulfillable, while still being able to meet the requirements. This we can fix relatively straight forward by again requiring that the source layout is one of the standard layouts. 

Another somewhat awkward thing is that subspan now gives the possibility to indirectly do 
```c++
basic_mdspan<...,layout_stride,...> a(...)
basic_mdspan<...,layout_left,...> b = a;
```
Also something we consciously not defined before, in order to keep complexity low. 

Our thinking was to later extend this with defining some `mapping_conversion<MappingA,MappingB>` class, which would introduce those capabilities, but leaving it for later.

**Comment by crtrott** [comment]
This is resolved: we are requiring `static_extent` preservation when using the `all_type` as a slice specifier for a `static_extent`.
